# Generated by Django 5.2.5 on 2025-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_director_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('company_admin', 'Director / Company Owner'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
